<?php

/**
 * @file
 * Functions to support theming in the SASS Starterkit subtheme.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_system_theme_settings_alter() for settings form.
 *
 * Replace Barrio setting options with subtheme ones.
 *
 * Example on how to alter theme settings form
 */
function hasco_barrio_form_system_theme_settings_alter(&$form, FormStateInterface $form_state) {
  $form['components']['navbar']['bootstrap_barrio_navbar_top_background']['#options'] = [
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  ];
  $form['components']['navbar']['bootstrap_barrio_navbar_background']['#options'] = [
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  ];
}

/**
 * Implements hook_preprocess_block().
 */
function hasco_barrio_preprocess_block(array &$variables) {
  // Verifica se o ID do bloco corresponde ao bloco "block-hasco-barrio-page-title".
  if (isset($variables['attributes']['id']) && $variables['attributes']['id'] === 'block-hasco-barrio-page-title') {
    // Verifica se o array de classes já existe.
    if (!isset($variables['attributes']['class'])) {
      $variables['attributes']['class'] = [];
    }

    // Adiciona a classe CSS 'mt-4' ao bloco correto.
    $variables['attributes']['class'][] = 'mt-4 mb-4';
  }
}




